### PR TITLE
Fix missing information bug in findClientID()

### LINKED ISSUE #216: top clients list has duplicates
@technicalpyro commented on [Tue Jan 23 2018](https://github.com/pi-hole/pi-hole/issues/1933)

**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{3}`

---
**Expected behaviour:**

web interface top clients lis not have duplicates with different query numbers

**Actual behaviour:**

**Steps to reproduce:**

`{run the dev branches  past that im unsure of what i did to cause this }`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`8jgnv8mc07`

**Troubleshooting undertaken, and/or other relevant information:**

`checked hosts file potentially that is causing the issues ?`

> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

Fixes #216 

When reading from `dnsmasq`'s log we always only got the IP address. We used internal name resolution to obtain a possible host name and stored both data in `FTL`'s internal data structure. However, when saving to `FTL`'s database, we only ever save the highest available level of data (that is we store the host name if it is available as host names <-> IP address correlations may change over time and having host names in the database seems to be the better choice in terms of archiving data).

On importing from the database, we erroneously copied the host name into the IP field of `FTL`'s internal data structure. This is not an issue and was not causing issues. However, if we now see of of the already known clients in `dnsmasq`'s log, we actually only see its IP address. We compare this IP address against all already known IP addresses and conclude that we have not seen this client before. Hence, we add a new client with the same host name.

This PR fixes this misbehavior by refining the algorithm from

1. Compare input string against all already known IP addresses
2. Create new client if no match was found

to
1. Compare input string against all already known IP addresses
2. If the input string is a valid IP address, we try to resolve it to a host name
3. If 2. was successful, we compare the host name we just obtained against all already known host names.
4. Create new client only if no match was found for all already known IP addresses and all already known host names.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

File: parser.c [hunk 1]
```diff
@@ -1186,25 +1198,63 @@ int findDomainID(const char *domain)
...
+	// a) new or
+	// b) only known by its hostname (after importing from the database)
+
+	// First try to resolve the IP to a hostname to compare again
+	char *hostname = NULL;
+	if(isValidIPv4(client) || isValidIPv6(client))
+	{
+		hostname = resolveHostname(client);
+
+		// Compare again with resolved host name if resoltuino succeeded
```
Comment (Mcat12) [inline parser.c]: Spelling error: `resolution`
