### PR TITLE
Fix possible crash if database is locked on startup

### LINKED ISSUE #625: SQLite3 message: database is locked in "SELECT VALUE FROM ftl WHERE id = 0;"
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_2_

---

**[BUG | ISSUE] Expected Behaviour:**
When restarting the DNS service with the following command:

```sh
sudo pihole restartdns
```
the DNS service should properly restart without crashing.

**[BUG | ISSUE] Actual Behaviour:**
When executing the command (see above), FTL reports the following error messages (entries taken from the log file under `/var/log/pihole-FTL.log`:

```log
[2019-07-30 16:30:20.036 1727] SQLite3 message: database is locked in "SELECT VALUE FROM ftl WHERE id = 0;" (5)
[2019-07-30 16:30:20.036 1727] db_query_int(SELECT VALUE FROM ftl WHERE id = 0;) - SQL error prepare (5): database is locked
[2019-07-30 16:30:20.036 1727] Database version is -2
[2019-07-30 16:30:20.036 1727] Database version incorrect, database not available
```

and FTL crashes. This behaviour does only occur after executing the restart command, not at normal startup.

This might be related to the merged PR #185 

**[BUG | ISSUE] Steps to reproduce:**

- execute `sudo pihole restartdns`

**Log file output [if available]**

see above

**Device specifics**

Hardware Type: rPi, VPS, etc
OS:
```
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10

Linux hostname 4.19.58-v7+ #1245 SMP Fri Jul 12 17:25:51 BST 2019 armv7l GNU/Linux

Pi-hole version v4.3.1
AdminLTE version is v4.3
FTL version is v4.3.1
```

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

## 10

---

Ensure we always initialize the database lock mutex even if an error causes us to return early in `db_init()`.

This PR fixes #625 (at least I assume this given the limited information available there so far).

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

File: src/database/common.c [hunk 1]
```diff
@@ -221,6 +221,17 @@ void db_init(void)
 		return;
 	}
 
+	// Initialize database lock mutex
+	if (pthread_mutex_init(&dblock, NULL) != 0)
+	{
+		logg("FATAL: FTL_db mutex init failed\n");
```
Comment (Mcat12) [inline src/database/common.c]: Is there some error output we can use to know why the mutex failed to initialize?
