### PR TITLE
Fix API specs and example for dns.upstreams in config.yaml

### LINKED ISSUE #2695: Documentation Bug, API
### Versions

- Pi-hole: Core version is v6.2.2 (Latest: v6.2.2)
- Web:  Web version is v6.3 (Latest: v6.3)
- FTL:  FTL version is v6.3.2 (Latest: v6.3.3)  

### Platform

- OS and version:  

- Platform:   Debian 10

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

Docs show wrong information.
Open Page
http://pi.hole/api/docs/#get-/config/-element

### Steps to reproduce

Open Page
1. http://pi.hole/api/docs/#get-/config/-element
2. Click on Fill Example button.

Example of element is: "dnsmasq/upstreams"
This should be "dns/upstreams"

## Debug Token

- URL:  

 https://tricorder.pi-hole.net/zV24Usq1/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by rdwebdesign**
### What does this PR aim to accomplish?

Fix #2695 

### How does this PR accomplish the above?

Replace "dnsmasq/upstreams" with the correct "dns/upstreams"

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by rdwebdesign** [comment]
Maybe we should fix the comments here too:

https://github.com/pi-hole/FTL/blob/d73944ac97408920ef415a9199708d279057c56b/src/api/config.c#L503-L504

**Review by yubiuser — DISMISSED** [review]

File: src/api/config.c [hunk 1]
```diff
@@ -500,8 +500,8 @@ int get_json_config(struct ftl_conn *api, cJSON *json, const bool detailed)
 				continue;
 			// Check equality of paths up to the requested level (if any)
 			// Examples:
-			//  requested was /config/dnsmasq -> skip all entries that do not start in dnsmasq.
-			//  requested was /config/dnsmasq/dhcp -> skip all entries that do not start in dhcp
+			//  requested was /config/dns -> skip all entries that do not start in dnsmasq.
```
Comment (DL6ER) [inline src/api/config.c]:
```suggestion
			//  requested was /config/dns -> skip all entries that do not start in dns
```
:thinking:

**Review by DL6ER — APPROVED** [review]
