### PR TITLE
Identify clients by hardware address not hardware + IP address

### LINKED ISSUE #576: Network table should only use hardware address to uniquely identify clients
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

## 10

---

**Preface**

Sequential DHCP servers may hand out different addresses to the same devices if they are connected in a different order. Pi-hole's own DHCP server tries to hand out the same addresses every time to the same devices (based on their hardware addresses).

**[BUG | ISSUE] Expected Behaviour:**

The network table should uniquely identify clients based on their hardware address (MAC).

**[BUG | ISSUE] Actual Behaviour:**

The network tables uses both the IP and the MAC to identify clients, causing identical devices that happen to have received different IP addresses as separate devices.

**[BUG | ISSUE] Steps to reproduce:**

- Use sequential DHCP server (`pihole-FTL` can do this when the setting `dhcp-sequential-ip` is used)
- Connect various devices in different chronological order
- Observe that the same devices are added multiple times

**Solution**

Only use MAC address to identify clients

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

This PR fixes #576. Further details can be found therein.

If multiple clients (with the same `hwaddr` but different IP addresses) have been added in the past, they will be fused to unique entries.

This PR bumps the database version to 4 without changing the structure. The version update is merely to signal that the unification of clients in the `network` table has been done on the given database.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

File: networktable.c [hunk 1]
```diff
@@ -86,15 +87,19 @@ void parse_arp_cache(void)
...
 
-		// Get ID of this device in our network database. If it cannot be found, then this is a new device
-		// We match both IP *and* MAC address
-		// Same MAC, two IPs: Non-deterministic DHCP server, treat as two entries
-		// Same IP, two MACs: Either non-deterministic DHCP server or (almost) full DHCP address pool
-		// We can run this SELECT inside the currently active transaction as only the
-		// changed to the database are collected for latter commitment. Read-only access
-		// such as this SELECT command will be executed immediately on the database.
+		// Get ID of this device in our network database. If it cannot be
+		// found, then this is a new device We only use the hardware address
```
Comment (Mcat12) [inline networktable.c]: Missing period.

File: networktable.c [hunk 2]
```diff
@@ -196,6 +208,93 @@ void parse_arp_cache(void)
...
+
+	// Ensure hwaddr is a unique field
+	// Unfortunately, SQLite's ALTER TABLE does not support adding
+	// constraints to existing tables. However, we can add a unique
+	// index for the table to achieve the same effect.
+	//
+	// See https://www.sqlite.org/lang_createtable.html#constraints:
+	// >>> In most cases, UNIQUE and PRIMARY KEY constraints are
+	// >>> implemented by creating a unique index in the database.
+	dbquery("CREATE UNIQUE INDEX hwaddr_idx ON network(hwaddr)");
```
Comment (Mcat12) [inline networktable.c]: The index name should be further namespaced in case we want to make a hwaddr index on another table. A better name would be `network_hwaddr_idx`

File: database.c [hunk 3]
```diff
@@ -264,6 +269,16 @@ void db_init(void)
 		dbversion = db_get_FTL_property(DB_VERSION);
 	}
 
+	//Update to version 4 if lower
+	if(dbversion < 4)
+	{
+		// Update to version 3: Create network table
```
Comment (Mcat12) [inline database.c]: This comment is incorrect

File: networktable.c [hunk 4]
```diff
@@ -196,6 +208,93 @@ void parse_arp_cache(void)
...
+	}
+
+	// Finalize statement and free query string
+	sqlite3_finalize(stmt);
+	free(querystr);
+
+	// Ensure hwaddr is a unique field
+	// Unfortunately, SQLite's ALTER TABLE does not support adding
+	// constraints to existing tables. However, we can add a unique
+	// index for the table to achieve the same effect.
```
Comment (Mcat12) [inline networktable.c]: What do you think of changing the table to use the MAC address as the primary key?

Comment (DL6ER) [reply networktable.c]: The `network` table has already been created for most. `ALTER TABLE` cannot be used to change the `PRIMARY KEY` and I don't think it would be worth creating a new and importing the old database table.

The current `id` column comes at no costs, as a column type `INTEGER PRIMARY KEY` is a mere alias for the `ROWID` which is always present (we're not using `AUTOINCREMENT` here).

File: database.c [hunk 5]
```diff
@@ -22,6 +22,9 @@ static pthread_mutex_t dblock;
 static bool db_set_counter(const unsigned int ID, const int value);
 static int db_get_FTL_property(const unsigned int ID);
 
+// defined in networktable.c
+extern bool unify_hwaddr(sqlite3 *db);
```
Comment (Mcat12) [inline database.c]: Would this be better in a header?

File: networktable.c [hunk 6]
```diff
@@ -15,6 +15,7 @@
 
 // Private prototypes
 static char* getMACVendor(const char* hwaddr);
+bool unify_hwaddr(sqlite3 *db);
```
Comment (Mcat12) [inline networktable.c]: If this is not used in this file, does it need to appear here?

File: database.c (hunk 5 above)
Comment (DL6ER) [reply database.c]: It cannot be written in `routines.h` as the datatype `sqlite3` is not known in this file. I'd like to refrain from including `sqlite3.h` in each file by adding it through `routines.h`.

File: networktable.c (hunk 6 above)
Comment (DL6ER) [reply networktable.c]: We enforce prototyping for all functions. Omitting the prototype would cause a compilation error. Typically, the prototype would be included through `routines.h`. Due to the reasons mentioned above (type `sqlite3` is unknown in `routines.h`), I added the prototype here.
