### PR TITLE
Fix FTL crash on closing handle to corrupted databases

### LINKED ISSUE #743: FTL does not start anymore
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1
---

**[BUG | ISSUE] Expected Behaviour:**
starting of pihole v5 does not work

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**Log file output [if available]**

[2020-05-02 16:36:14.943 6309] SQLite3 message: no such table: domain_audit in "SELECT EXISTS(SELECT domain, CASE WHEN substr(domain, 1, 1) = '*' THEN '*' || substr(:input, - length(domain) + 1) ELSE :input END matcher FROM domain_audit WHERE matcher = doma (1)
[2020-05-02 16:36:14.943 6309] gravityDB_open("SELECT EXISTS(... domain_audit ...)") - SQL error prepare: SQL logic error
[2020-05-02 16:36:14.943 6309] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-05-02 16:36:14.943 6309] ---------------------------->  FTL crashed!  <----------------------------
[2020-05-02 16:36:14.943 6309] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-05-02 16:36:14.943 6309] Please report a bug at https://github.com/pi-hole/FTL/issues
[2020-05-02 16:36:14.943 6309] and include in your report already the following details:
[2020-05-02 16:36:14.943 6309] FTL has been running for 0 seconds
[2020-05-02 16:36:14.943 6309] FTL branch: release/v5.0
[2020-05-02 16:36:14.943 6309] FTL version: vDev-5b0cfb5
[2020-05-02 16:36:14.943 6309] FTL commit: 5b0cfb5
[2020-05-02 16:36:14.944 6309] FTL date: 2020-04-28 21:05:08 +0200
[2020-05-02 16:36:14.944 6309] FTL user: started as pihole, ended as pihole
[2020-05-02 16:36:14.944 6309] Compiled for armhf (compiled on CI) using arm-linux-gnueabihf-gcc (Debian 6.3.0-18) 6.3.0 20170516
[2020-05-02 16:36:14.944 6309] Received signal: Segmentation fault
[2020-05-02 16:36:14.944 6309]      at address: 0x8
[2020-05-02 16:36:14.944 6309]      with code: SEGV_MAPERR (Address not mapped to object)
[2020-05-02 16:36:14.944 6309] Backtrace:
[2020-05-02 16:36:14.944 6309] B[0000]: 0x4f7928, /usr/bin/pihole-FTL(+0x23928) [0x4f7928]
[2020-05-02 16:36:14.944 6309] B[0001]: 0xb6d95130, /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb6d95130]
[2020-05-02 16:36:14.944 6309] B[0002]: 0x4f0e54, /usr/bin/pihole-FTL(+0x1ce54) [0x4f0e54]
[2020-05-02 16:36:14.944 6309] B[0003]: 0x4f1062, /usr/bin/pihole-FTL(+0x1d062) [0x4f1062]
[2020-05-02 16:36:14.944 6309] B[0004]: 0x4f16f2, /usr/bin/pihole-FTL(gravityDB_open+0x2d) [0x4f16f2]
[2020-05-02 16:36:14.944 6309] B[0005]: 0x4f77d2, /usr/bin/pihole-FTL(FTL_reload_all_domainlists+0x11) [0x4f77d2]
[2020-05-02 16:36:14.944 6309] B[0006]: 0x4fb9a4, /usr/bin/pihole-FTL(FTL_dnsmasq_reload+0xe7) [0x4fb9a4]
[2020-05-02 16:36:14.944 6309] B[0007]: 0x51c168, /usr/bin/pihole-FTL(clear_cache_and_reload+0x17) [0x51c168]
[2020-05-02 16:36:14.944 6309] B[0008]: 0x51d6c0, /usr/bin/pihole-FTL(main_dnsmasq+0x12cb) [0x51d6c0]
[2020-05-02 16:36:14.944 6309] B[0009]: 0x4edda8, /usr/bin/pihole-FTL(main+0xa7) [0x4edda8]
[2020-05-02 16:36:14.944 6309] B[0010]: 0xb6d7f718, /lib/arm-linux-gnueabihf/libc.so.6(__libc_start_main+0x10c) [0xb6d7f718]
[2020-05-02 16:36:14.945 6309] ------ Listing content of directory /dev/shm ------
[2020-05-02 16:36:14.945 6309] File Mode User:Group  Filesize Filename
[2020-05-02 16:36:14.945 6309] rwxrwxrwx root:root 280 .
[2020-05-02 16:36:14.945 6309] rwxr-xr-x root:root 4K ..
[2020-05-02 16:36:14.945 6309] rw------- pihole:pihole 4K FTL-per-client-regex
[2020-05-02 16:36:14.945 6309] rw------- pihole:pihole 4K FTL-dns-cache
[2020-05-02 16:36:14.945 6309] rw------- pihole:pihole 29K FTL-overTime
[2020-05-02 16:36:14.945 6309] rw------- pihole:pihole 229K FTL-queries
[2020-05-02 16:36:14.945 6309] rw------- pihole:pihole 20K FTL-upstreams
[2020-05-02 16:36:14.945 6309] rw------- pihole:pihole 643K FTL-clients
[2020-05-02 16:36:14.946 6309] rw------- pihole:pihole 66K FTL-domains
[2020-05-02 16:36:14.946 6309] rw------- pihole:pihole 8K FTL-strings
[2020-05-02 16:36:14.946 6309] rw------- pihole:pihole 12 FTL-settings
[2020-05-02 16:36:14.946 6309] rw------- pihole:pihole 124 FTL-counters
[2020-05-02 16:36:14.946 6309] rw------- pihole:pihole 28 FTL-lock
[2020-05-02 16:36:14.946 6309] rw-r--r-- fr24:fr24 2K decoder.txt
[2020-05-02 16:36:14.946 6309] ---------------------------------------------------
[2020-05-02 16:36:14.946 6309] Thank you for helping us to improve our FTL engine!
[2020-05-02 16:36:14.946 6309] FTL terminated!

**Device specifics**

Hardware Type: Raspberry Pi
OS:

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

When FTL detects that `gravity.db` has been corrupted in any way (maybe a user deleted an essential table within the database, or the database is malformed due to I/O issues such as unrecoverable power-loss failures), it tries to release all allocated memory for this database. Unfortunately, this could have given rise to a crash under certain conditions when trying to free memory which wasn't allocated. This could have happened when we failed very early in preparing the database statements, such as during the preparation of the audit-list table statement.

We fix this by ensuring that invoking `free_sqlite3_stmt_vec()` on a `NULL` pointer is a harmless no-op. This routine will now simply do nothing if there isn't any memory to be freed.

Fixes #743 and some other issue I recall having seen on our Discourse forum.

### CODE REVIEW

File: src/database/gravity-db.c [hunk 1]
```diff
@@ -733,7 +748,7 @@ bool in_gravity(const char *domain, const int clientID, clientsData* client)
 	// Update statement if has just been initialized
 	if(stmt == NULL)
 	{
-		stmt = whitelist_stmt->get(whitelist_stmt, clientID);
```
Comment (DL6ER) [inline src/database/gravity-db.c:736]: This was incorrect and gets fixed here as well. It is fallback code which is likely why we have never seen reports for this. Same below.
