### PR TITLE
Do not overwrite externally given MAKEFLAGS if set

### LINKED ISSUE #2358: MAKEFLAG `-j` is overwritten in build.sh
### Versions

- Pi-hole:  6.0.4
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  Arch

- Platform:  Raspberry Pi 3

### Expected behavior

MAKEFLAGS (especially `-j`) are not overwritten in the build.sh. Setting default values if the flags are not supplied would be perfect but they should not take precedence over ones beeing set on the system.

### Actual behavior / bug

Currently in the build.sh script (line 161 `cmake --build . -- -j "$(nproc)"`) overwrites the `-j` option to the number of processors on the system. While this is fine for most systems on memory constrained ones this makes it impossible to build. (1Gb on RPi3)

### Steps to reproduce

1. Set MAKEFLAGS Env var with `-j 1`
2. run build.sh
3. see that the build uses more than one processor

### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

A very simple change, see #2358 for more context.

---

**Related issue or feature (if applicable):** Fixes #2358

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

File: build.sh [hunk 1]
```diff
@@ -157,8 +157,13 @@ else
     cmake ..
 fi
 
-# Build the sources with the number of available cores
-cmake --build . -- -j "$(nproc)"
+# If MAKEFLAGS is unset, we set it to "-j$(nproc)"
+if [[ -z "${MAKEFLAGS}" ]]; then
+    export MAKEFLAGS="-j$(nproc)"
```
Comment (yubiuser) [inline build.sh:162]: Why do we need to export them?

Comment (DL6ER) [reply build.sh:162]: To not duplicate the `cmake` command in the `if` statement

**Review by yubiuser — APPROVED** [review]
