### PR TITLE
Fix overTime data when database.DBimport = false

### LINKED ISSUE #2785: Total queries timeline not advancing when logging is disabled
### Versions

- Pi-hole:  v6.4
- Web:  v6.4.1
- FTL:  v6.5

### Platform

- OS and version:  Debian 13 Trixie / Linux pi 6.12.62+rpt-rpi-v8
- Platform:  Raspberry Pi 4 Model B Rev 1.1

### Expected behavior

The total queries timeline should advance as usual.

### Actual behavior / bug

The total queries timeline collects all queries at the 10min when pihole-FTL was restarted at the right of the timeline. Enabling logging resolves this issue and everything works as expected. Re-disabling query logging and setting anonymous mode brings the error back.

### Steps to reproduce

1. Go to 'Settings/Privacy'
2. Deselect 'Log DNS queries and replies' then enable 'Anonymous mode'
3. Watch the total queries timeline in the dashboard

## Debug Token

- URL:  https://tricorder.pi-hole.net/2JySHl8x/

### Screenshots

Image

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

Always mark database import as done even when `database.DBimport = false` or on database errors.

Otherwise, garbage collection will never run, causing the memory allocation to always grow and overtime information to be incorrect (handled in GC code as well)

---

**Related issue or feature (if applicable):** Fixes #2785 

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `development` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

File: src/database/database-thread.c [hunk 1]
```diff
@@ -153,6 +155,9 @@ void *DB_thread(void *val)
 	if(config.database.DBimport.v.b)
 		DB_read_queries();
 
+	// Signify that the import is done, so garbage collection will run
+	db_import_done = true;
+
```
Comment (rdwebdesign) [inline src/database/database-thread.c:160]: This is a question:

The new code always sets `db_import_done = true`.

Before the change, did the `DB_read_queries()` function always modify the value of `db_import_done` to `true`, or was there a possibility that this variable would still be `false`?

In other words, should we use the original `query-table.c` and only add an `else` here?

```suggestion
	else
	{
		// Signify that the import is done, so garbage collection will run
		db_import_done = true;
	}

```

Comment (DL6ER) [reply src/database/database-thread.c:160]: > Before the change, did the DB_read_queries() function always modify the value of db_import_done to true, or was there a possibility that this variable would still be false?

This is the perfect place to respond with the German word: Jein (a blend of Yes and No).

---

The function did set `db_import_done = true`, however, not always. When there were database importing issues (like a corrupted database), it would *not* have set it to `true`, i.e., in this case the garbage collection (GC) would never run, the in-memory database would grow ever larger and the "everything in the last slot issue" would persist, too.

The only effect of `db_import_done` is postponing any possible GC run until we are sure database import isn't running any longer. Even when it failed, it won't happen again, hence, it is fine to set it unconditionally as I did here.

Comment (rdwebdesign) [reply src/database/database-thread.c:160]: OK.

**Comment by DL6ER** [comment]
Confirmed working by OP in https://github.com/pi-hole/FTL/issues/2785#issuecomment-3977307090

**Review by rdwebdesign — APPROVED** [review]
