### PR TITLE
Fix/privacy levels regex filtering

### LINKED ISSUE #414: Broken: Fix for regex filters + privacy level > 0
Looks like this fix does not work anymore:
https://github.com/pi-hole/FTL/pull/331

I can reproduce this behavior with the latest version of Pi Hole on different machines.

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

## 10

---

Fix regex filtering when privacy levels is > 0. This fixes #414 

When a new query comes in, we check if we know this domain already.

If so: We check against the regex filters. If one of the filters match, we inject the domain as blocked into our DNS cache.
If not: We continue.

When the same domains is queried another time, we don't evaluate the regex filters any more as we rely on that the query will be quickly replied to from cache.

This usually works fine, however, for a non-zero privacy level, all domains are only stored as `hidden` in FTL's memory. Accordingly, any subsequent query (after the first )is not validated against the regex filters any more as they all get the same `domainID`.

This has been fixed.
**As a consequence, you cannot lower the privacy level without restarting `pihole-FTL`**!

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

File: dnsmasq_interface.c [hunk 1]
```diff
@@ -167,7 +150,12 @@ void FTL_new_query(unsigned int flags, char *name, struct all_addr *addr, char *
 	queries[queryID].db = false;
 	queries[queryID].id = id;
 	queries[queryID].complete = false;
-	queries[queryID].private = (config.privacylevel == PRIVACY_MAXIMUM);
+
+	// Check and apply possible privacy level rules
+	// We do this immediately on the raw data to avoid any possible leaking
```
Comment (Mcat12) [inline dnsmasq_interface.c]: The second line of this comment may need to be tweaked, since no data is modified by getting the privacy level. Instead, the current privacy level is remembered for that query.

File: datastructure.c [hunk 2]
```diff
@@ -234,3 +234,25 @@ bool isValidIPv6(const char *addr)
...
+	if(queries[queryID].privacylevel < PRIVACY_HIDE_DOMAINS)
+	{
+		validate_access("domains", queries[queryID].domainID, true, __LINE__, __FUNCTION__, __FILE__);
+		return domains[queries[queryID].domainID].domain;
+	}
+	else
+		return HIDDEN_DOMAIN;
+}
+
+char *getClientString(int queryID)
```
Comment (Mcat12) [inline datastructure.c]: The function name should indicate that it returns the client IP, not the name

File: api.c [hunk 3]
```diff
@@ -402,10 +403,6 @@ void getTopClients(char *client_message, int *sock)
 			(insetupVarsArray(clients[j].ip) || insetupVarsArray(clients[j].name)))
 			continue;
 
-		// Hidden client, probably due to privacy level. Skip this in the top lists
-		if(strcmp(clients[j].ip, "0.0.0.0") == 0)
-			continue;
```
Comment (Mcat12) [inline api.c]: I don't see a call to `getClientString` to replace this code.

Comment (DL6ER) [reply api.c]: At the very beginning of this subroutine, we just terminate if the privacy level is high enough that client IPs are hidden. As the privacy level cannot be lowered on-the-fly any longer, we can never get into a situation where the loop would run over any queries with a sufficient privacy level due to this early returning.

Comment (Mcat12) [reply api.c]: If FTL is restarted with a lower privacy level, then it could loop over queries which were saved in the database with hidden client IPs. Would we still want to hide those?

Comment (DL6ER) [reply api.c]: Hmm, I agree that having the Top Items being dominated by `hidden` resp. `0.0.0.0` doesn't make much sense. I will reimplement the code to skip such entries in the Top Item replies.
