### PR TITLE
Change default file serving behavior **possibly breaking**

### LINKED ISSUE #2349: Pihole 6 webserver exposes code from other files on regular webserver
### Versions

- Pi-hole:  6.0.5
- AdminLTE:  6.0.2
- FTL:  6.0.4

### Platform

- OS and version:  Ubuntu 24.04

- Platform:  x86 bare metal

### Expected behavior

the pihole webserver should only display or execute files in the defined subpath

### Actual behavior / bug

default webroot is a `/var/www/html/` so if I open the pihole webserver over `https://127.0.0.1:8443` it exposes the code of my index.php. This happens to all files on the webserver.
The pihole webserver should be blocking everything, which isn't in the defined subpath or redirect to the subpath.

### Steps to reproduce

1. open the pihole webserver without subpath

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

Add new `webserver.serve_all` option defaulting to `false`, controlling if we should serve any content outside `/admin` and `/api`.

---

**Related issue or feature (if applicable):** Fixes #2349 

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

File: src/webserver/lua_web.c [hunk 1]
```diff
@@ -80,6 +80,18 @@ int request_handler(struct mg_connection *conn, void *cbdata)
...
 	}
 
+	// Check if we are allowed to serve this directory by checking the
+	// configuration setting webserver.serve_all and the requested URI to
+	// start with something else than config.webserver.paths.webhome. If so,
+	// send error 404
+	if(!config.webserver.serve_all.v.b &&
+	   strncmp(req_info->local_uri_raw, config.webserver.paths.webhome.v.s, strlen(config.webserver.paths.webhome.v.s)) != 0)
+	{
+		log_debug(DEBUG_API, "Not serving %s, returning 404", req_info->local_uri_raw);
```
Comment (yubiuser) [inline src/webserver/lua_web.c:90]:
```suggestion
		log_debug(DEBUG_WEBSERVER, "Not serving %s, returning 404", req_info->local_uri_raw);
```

File: src/webserver/webserver.c [hunk 2]
```diff
@@ -127,6 +127,20 @@ static int redirect_lp_handler(struct mg_connection *conn, void *input)
...
 	const size_t uri_len = strlen(uri);
+
+	// Check if we are allowed to serve this directory by checking the
+	// configuration setting webserver.serve_all and the requested URI to
+	// start with something else than config.webserver.paths.webhome. If so,
+	// send error 404
+	if(!config.webserver.serve_all.v.b &&
+	   strncmp(uri, config.webserver.paths.webhome.v.s, strlen(config.webserver.paths.webhome.v.s)) != 0)
+	{
+		log_debug(DEBUG_API, "Not serving %s, returning 404", uri);
```
Comment (yubiuser) [inline src/webserver/webserver.c:138]:
```suggestion
		log_debug(DEBUG_WEBSERVER, "Not serving %s, returning 404", uri);
```

**Comment by DL6ER** [comment]
Seems this is a wanted feature, I can already hear the complaints but let's try to make it as clear as possible in the changelog and release notes. Ready for review.

**Review by yubiuser — APPROVED** [review]
