### PR TITLE
home.arpa and internal TLDs may be non-local without revServer

### LINKED ISSUE #2769: Cannot forward home.arpa unless revServer configured, even when pihole domain is home.arpa
### Versions
Core version is v6.3 (Latest: v6.3)
Web version is v6.4 (Latest: v6.4)
FTL version is v6.4.1 (Latest: v6.4.1)

### Platform

- OS and version:  Debian 12 

- Platform:  Proxmox LXC

### Expected behavior

My chosen domain for internal servers is home.arpa.  My goal is to have pihole handle only DNS blocking, and forward all other requests to opnsense for local name resolution and forwarding to unbound.  So I simply set my upstream to opnsense and that should be all.

### Actual behavior / bug

However, it's hard coded that home.arpa is set to local in dnsmasq.conf unless there's a revServer with home.arpa as the domain, so my desired configuration cannot be done - any lookups for X.home.arpa never get forwarded past pihole and there is no way to change it other than setting a revServer, which I do not want to do.

### Steps to reproduce

1. set upstream dns to a router that can resolve X.home.arpa
2. clear all revServers
3. nslookup X.home.arp
4. You'll get NXdomain and the query is never forwarded to upstream

## Debug Token

- URL:  https://tricorder.pi-hole.net/yGothn8m/

### Additional context

I see two possible solutions here.

When flagging domain_homearpa, make it so that if pihole's domain is home.arpa, and dhcp is not in use, it will forward home.arpa upstream. This does make some assumptions though and may not be the best.

A simple solution would just be an option flag "Allow forwarding of home.arpa to upstream" so it's a conscious decision by the user to allow this for their specific setup.

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

Fix that `dns.domain = "home.arpa"` ( or `"internal"`) **and** `dns.domain.local = false` should result in these domains being sent to regular upstreams - even in the absence of matching `revServer` settings. So far, a valid `revServer` line for this configuration is needed to function as expected.

This is a direct fix for #2769 

---

**Related issue or feature (if applicable):**  Closes #2769

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `development` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Review by Aerankas — APPROVED** [review]
My vote doesn't count, but looks good to me and thanks for the fix.

**Comment by yubiuser** [comment]
@Aerankas did you actually test this brach in your setup?

You can switch to this implementation by runing

`pihole checkout ftl fix/dns_domain_local`

**Comment by Aerankas** [comment]
I did attempt to verify this, thanks for the command to switch to dev branch.  I left revServers blank, set dns.domain.name to home.arpa and dns.domain.local to disabled, as I wanted.  I can see the dnsmasq.conf line  (local=/home.arpa/) is gone.  However I can't seem to resolve a home.arpa address (NXDOMAIN).  This could be a problem on my end since I did change to a different domain and tried to just create a test - In opnsense unbound I set query forwarding for home.arpa to point to dnsmasq. In dnsmasq I added a hosts record with name piholeverify, domain home.arpa and a valid IP on my network.  I'm not yet sure where the request is failing.
Edit: nslookup direct to opnsense also returns NXDOMAIN, so I think it's possible the request is being forwarded correctly and my test setup is poor.

**Comment by Aerankas** [comment]
I was able to set up a proper test and unfortunately it's not working as expected.

Direct to opnsense works:

nslookup piholeverify.home.arpa 192.168.0.1
Server:  opnsense.lan
Address:  192.168.0.1

Name:    piholeverify.home.arpa
Address:  192.168.0.10

Via pihole fails (it's forwarding to 192.168.0.1):
nslookup piholeverify.home.arpa
Server:  pi.hole
Address:  192.168.1.10

*** pi.hole can't find piholeverify.home.arpa: Non-existent domain

**Comment by Aerankas** [comment]
Ah. It's appending .lan which is why it fails.

root@pihole:/etc/pihole# pihole -t | grep home.arpa
Feb  3 11:01:55: query[A] piholeverify.home.arpa.lan from 192.168.0.50
Feb  3 11:01:55: forwarded piholeverify.home.arpa.lan to 192.168.1.1
Feb  3 11:01:55: reply piholeverify.home.arpa.lan is NXDOMAIN

That's probably my connection-specific suffix? I tried setting is manually to prevent this (I'm committed to keeping my internal domain as .lan now so I don't want to reconfigure it back to home.arpa, so the testing is a little finicky).

Now I can see both the .lan request and the proper request, but getting a cached nxdomain

root@pihole:/etc/pihole# pihole -t | grep home.arpa
Feb  3 11:19:13: query[A] piholeverify.home.arpa.lan from 192.168.0.50
Feb  3 11:19:13: forwarded piholeverify.home.arpa.lan to 192.168.1.1
Feb  3 11:19:13: reply piholeverify.home.arpa.lan is NXDOMAIN
Feb  3 11:19:13: query[AAAA] piholeverify.home.arpa.lan from 192.168.0.50
Feb  3 11:19:13: forwarded piholeverify.home.arpa.lan to 192.168.1.1
Feb  3 11:19:13: reply piholeverify.home.arpa.lan is NXDOMAIN
Feb  3 11:19:13: query[A] piholeverify.home.arpa from 192.168.0.50
Feb  3 11:19:13: cached piholeverify.home.arpa is NXDOMAIN
Feb  3 11:19:13: query[AAAA] piholeverify.home.arpa from 192.168.0.50
Feb  3 11:19:13: cached piholeverify.home.arpa is NXDOMAIN

**Comment by Aerankas** [comment]
And it works!

root@pihole:/etc/pihole# pihole reloaddns
  [✓] Flushing DNS cache
root@pihole:/etc/pihole# pihole -t | grep home.arpa
Feb  3 11:22:02: query[A] piholeverify.home.arpa.lan from 192.168.0.50
Feb  3 11:22:02: forwarded piholeverify.home.arpa.lan to 192.168.1.1
Feb  3 11:22:02: reply piholeverify.home.arpa.lan is NXDOMAIN
Feb  3 11:22:02: query[AAAA] piholeverify.home.arpa.lan from 192.168.0.50
Feb  3 11:22:02: forwarded piholeverify.home.arpa.lan to 192.168.1.1
Feb  3 11:22:02: reply piholeverify.home.arpa.lan is NXDOMAIN
Feb  3 11:22:02: query[A] piholeverify.home.arpa from 192.168.0.50
Feb  3 11:22:02: forwarded piholeverify.home.arpa to 192.168.1.1
Feb  3 11:22:02: reply piholeverify.home.arpa is 192.168.0.10
Feb  3 11:22:02: query[AAAA] piholeverify.home.arpa from 192.168.0.50
Feb  3 11:22:02: forwarded piholeverify.home.arpa to 192.168.1.1
Feb  3 11:22:02: reply piholeverify.home.arpa is NODATA-IPv6

**Comment by yubiuser** [comment]
Thanks for testing!

File: src/config/dnsmasq_config.c [hunk 1]
```diff
@@ -571,17 +569,26 @@ bool __attribute__((nonnull(1,3))) write_dnsmasq_config(struct config *conf, boo
...
-	// Ensure that home.arpa domains (RFC 8375) are not sent upstream, unless configured by
-	// user as local domain, with server setting applied above
-	if (!domain_homearpa)
+	// Ensure that home.arpa domains (RFC 8375) are not sent upstream,
+	// unless explicitly configured by user as local domain with either:
+	//  - revServer entry for "home.arpa" (revServer_homearpa), or
+	//  - dns.domain == "home.arpa" AND dns.domain.local == false
+	const bool domain_homearpa = strlen(conf->dns.domain.name.v.s) > 0 &&
+	                             strcasecmp(conf->dns.domain.name.v.s, "home.arpa") == 0;
+	if (!revServer_homearpa && !domain_homearpa && !config.dns.domain.local.v.b)
```
Comment (yubiuser) [inline src/config/dnsmasq_config.c]: Shouldn't this be something like


```suggestion
	if ((!revServer_homearpa) ||(!domain_homearpa && !config.dns.domain.local.v.b))
```

This would reflect what is written in the comment above.

Comment (rdwebdesign) [reply src/config/dnsmasq_config.c]: Or maybe the comment should be fixed to reflect what the code does.

**Comment by andreasbehnke** [comment]
I had the exact same problem (using upstream DNS for resolving local hosts to FQN xyz.home.arpa) and setting domain name to home.arpa and local to false plus checking out this branch fixed it.

File: src/config/dnsmasq_config.c (hunk 1 above)
Comment (DL6ER) [reply src/config/dnsmasq_config.c]: Yes, the code logic is broken. It should look like
``` c
if (!revServer_internal && !(domain_internal && !config.dns.domain.local.v.b))
```
to add `local=/internal/` unless a matching `rev-server` exists or the domain is `internal` with `domain.local == false`

The suggestion above would always add the protection when there is no rev-server, regardless of the `domain_homearpa` and `config.dns.domain.local.v.b` values.

However, we only want the protection if
- no rev server is configured AND
- the domain is `internal` AND `domain.local == false`

What makes the comment a bit harder to understand is that its intent is negated by itself (add the lines unless ...) but the `if` is formulated positively. I will clarify the comment as well.

File: src/config/dnsmasq_config.c [hunk 2]
```diff
@@ -571,17 +569,30 @@ bool __attribute__((nonnull(1,3))) write_dnsmasq_config(struct config *conf, boo
...
```
Comment (yubiuser) [inline src/config/dnsmasq_config.c]:
```suggestion
	if (!revServer_homearpa && !(domain_homearpa && config.dns.domain.local.v.b == false))
```

**Review by yubiuser — COMMENTED** [review]
I still find it confusing that the comments talk about two conditions connected with OR but the code only uses AND. But maybe need a fresh look tomorrow.

File: src/config/dnsmasq_config.c (hunk 2 above)
Comment (DL6ER) [reply src/config/dnsmasq_config.c]: `!revServer_homearpa && !(domain_homearpa && !config.dns.domain.local.v.b)`

For brevity, let's use `R=revServer`, `D=domain`, `L=domain.local`:

- If the user explicitly set the domain to `home.arpa` and marked it non-local (`D=true`, `L=false`) we must NOT add the protection.
  - Your initial suggestion `(!R) || (!D && !L)` evaluates to `true` when `R=false` and so would still add the protection — incorrect.
  - My `!R && !(D && !L)` evaluates to `false` (doesn't add protection) — correct.

- If a `revServer` exists (`R=true`) we must NOT add the protection.
  - Your initial variant can still be `true` when `R=true` if `(!D && !L)` is `true`, so it may add protection despite a `revServer` — incorrect.
  - My variant is false when `R=true` — correct.

The comment yields the exception condition `(R || (D && !L))` the protection should be **the negation of that**: `!R && !(D && !L)`. We can write `!(R || (D && !L))` which is the same expression just needing more steps for evaluation. However, if it makes things more readable, this is justified.

Comment (DL6ER) [reply src/config/dnsmasq_config.c]: I pushed a major simplification. I hope this is now clear.

**Review by yubiuser — APPROVED** [review]
Now a simple mind can understand this as well :-)
