### PR TITLE
Fixes incorrect "Found unknown status 14 in long term database" warning

### LINKED ISSUE #1045: Warning: Found unknown status 14 in long term database!
### Versions
```
nanopi@nanopi:~$ pihole -v
  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is devel v5.3.2-1-g6ff083a7 (Latest: v5.3.2)
  FTL version is development vDev-d4cb03c (Latest: v5.6)
```

After a restart of Pi-hole I get some warnings regarding the unknown status type 14

```
[2021-01-28 14:40:30.461 10850M] Warning: Found unknown status 14 in long term database!
[2021-01-28 14:40:30.468 10850M] Warning: Found unknown status 14 in long term database!
[2021-01-28 14:40:30.472 10850M] Warning: Found unknown status 14 in long term database!
[2021-01-28 14:40:30.482 10850M] Warning: Found unknown status 14 in long term database!
[2021-01-28 14:40:30.482 10850M] Warning: Found unknown status 14 in long term database!
[2021-01-28 14:40:30.490 10850M] Warning: Found unknown status 14 in long term database!
[2021-01-28 14:40:30.490 10850M] Warning: Found unknown status 14 in long term database!
[2021-01-28 14:40:30.492 10850M] Warning: Found unknown status 14 in long term database!

```

Has the new type been forgotten somewhere in https://github.com/pi-hole/FTL/commit/6bb025faec41a465727b88cdc4881d7c64d59eb5

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

Fixes incorrect "Found unknown status 14 in long term database" warning in the logs. We change the code to use a enum-based struct so we cannot forget to update this in the future when adding further query status types.

Fixes #1045

### CODE REVIEW

File: src/database/query-table.c [hunk 1]
```diff
@@ -535,9 +536,11 @@ void DB_read_queries(void)
 
 			case QUERY_RETRIED: // Retried query
 			case QUERY_RETRIED_DNSSEC: // fall through
+			case QUERY_IN_PROGRESS:
```
Comment (DL6ER) [inline src/database/query-table.c:539]: Adding this line silences the incorrect warning.

File: src/database/query-table.c [hunk 2]
```diff
@@ -359,12 +359,13 @@ void DB_read_queries(void)
...
-		const int status = sqlite3_column_int(stmt, 3);
-		if(status < QUERY_UNKNOWN || status >= QUERY_STATUS_MAX)
+		const int status_int = sqlite3_column_int(stmt, 3);
+		if(status_int < QUERY_UNKNOWN || status_int >= QUERY_STATUS_MAX)
 		{
-			logg("FTL_db warn: STATUS should be within [%i,%i] but is %i", QUERY_UNKNOWN, QUERY_STATUS_MAX-1, status);
+			logg("FTL_db warn: STATUS should be within [%i,%i] but is %i", QUERY_UNKNOWN, QUERY_STATUS_MAX-1, status_int);
 			continue;
 		}
+		const enum query_status status = status_int;
```
Comment (DL6ER) [inline src/database/query-table.c:368]: This change ensures we cannot forget to add new status types in the future (the `switch` statement would complain during compilation, otherwise).

**Review by dschaper — APPROVED** [review]
